<a href="https://colab.research.google.com/github/Hamid-Mofidi/Python_Intro/blob/main/Pyth_intro_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In Python, **indexing** refers to the process of accessing a specific element in a sequence, such as a string or list, using its position or index number. **Indexing** in Python starts at 0, which means that the first element in a sequence has an index of 0, the second element has an index of 1, and so on.


In [13]:
# indexing
alst = [2, -1, 4, 5.4, 'sdtr', -2.43, [10, 20, 30]]
print(alst[3])
print(alst[len(alst)-1])  # this gives the last element of the list, but this is not the simplest way to call it
print(alst[-1] )    # this way we can simply find the last element
print(alst[-2])
# Question: How can we catch the number 20 inside the list imbeded in "alst"?
alst[-1][1]

5.4
[10, 20, 30]
[10, 20, 30]
-2.43


20

In [25]:
# Exercise!
blst = [2, 'hi', [3, 5, 9] , {'dog': 'cute', 'cat' : 'naughty'  }]
type(blst[-1])
# Get the character of dog from above list!
blst[-1]['dog']

'cute'

**slice()** function in python is used to extract a continuous sequence(it may be an empty sequence, complete sequence or a partial sequence) of any object(array, string, tuple) . It returns a slice object which can be used with the array/string which will return the continuous sequence after slicing.

In [1]:
# slicing
a = range(2, 8)
print(type(a))
print(a[0])
print(a[-1])
print(a)
print(a[0:3])

<class 'range'>
2
7
range(2, 8)
range(2, 5)


In [2]:
lst = list(a)
print(lst)
print(type(lst))
print(lst[0:3])
print(lst[:2])
print(lst[2:])
# last[start:stop:skip] 
print(lst[::2]) # this means we want all elements and then we want to skip by two

[2, 3, 4, 5, 6, 7]
<class 'list'>
[2, 3, 4]
[2, 3]
[4, 5, 6, 7]
[2, 4, 6]


In [49]:
# reverse a list
print(lst[::-1])

print(lst[::-2]) # this means we want all elements (backward) and then we want to skip by two 
print(lst[1::2]) # to get odd elements

[7, 6, 5, 4, 3, 2]
[7, 5, 3]
[3, 5, 7]


In [56]:
# functions
print(sum(a))
print(sum(lst))

output = sum(lst) -2
print('The sum minus two is' +' ' + str(output))


27
27
The sum minus two is 25


**NumPy** is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

In [79]:
# Numpy
import numpy as np

num = list(range (2,7))
print(num)
print(np.mean(num))

#the other way to find mean using numpy:
num2 = np.array(num)
print(num2)
print(num2.mean() )

num2.max()



[2, 3, 4, 5, 6]
4.0
[2 3 4 5 6]
4.0


6

Note that instead importing the whole numpy library, we could just import the function we need on that library. For example, in the following, we import 'mean' from numpy. 
(Remark: '**Runtime + Restart runtime**' will restart the session.)

In [80]:
print(np.linspace(2,8,4))
b = np.linspace(0,1,5)
print(type(b))
print(b)


[2. 4. 6. 8.]
<class 'numpy.ndarray'>
[0.   0.25 0.5  0.75 1.  ]


In [9]:
from numpy import mean as mn
mn(lst)

4.5

**Pandas** is a Python library used for working with data sets . It has functions for analyzing, cleaning, exploring, and manipulating data. The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

In [26]:
import numpy as np
import pandas as pd

# create random data
rand1 = np.random.randn()  # it returns a random number drawn from Gaussian distribution or a normal distribution
rand2 = np.random.randn(5)  # it returns 5 random number
rand3 = np.random.randn(2,3)  # it returns a 2x3 matrix

print(rand1)
print(type(rand1))
print(rand2)
print(type(rand2))
print(rand3)
type(rand3)

0.8361771025444888
<class 'float'>
[ 0.00896626 -2.23299819  1.16045441 -0.60227936 -0.59765156]
<class 'numpy.ndarray'>
[[ 1.02260921  1.05198469 -0.08996995]
 [-0.32808657  0.09448729  0.87390032]]


numpy.ndarray

In [33]:
# variable lables
labels = ['Temp(c)', 'Ice cream']
print(type(labels))

#put them together in a dictionary
# DD= { labels[0]: rand2[::2] , labels[1]: rand2[1::2] }   # I am not using this data because further pandas cannot run 
# as "All arrays must be of the same length" for using datagram. So we use the following data DD
DD= { labels[0]: rand2 , labels[1]: rand2[::-1] } 
print(DD)
print(type(DD))

#import the dictionary into a pandas dataframe
df = pd.DataFrame(data=DD)
print(df)
print(df.count())

<class 'list'>
{'Temp(c)': array([ 0.00896626, -2.23299819,  1.16045441, -0.60227936, -0.59765156]), 'Ice cream': array([-0.59765156, -0.60227936,  1.16045441, -2.23299819,  0.00896626])}
<class 'dict'>
    Temp(c)  Ice cream
0  0.008966  -0.597652
1 -2.232998  -0.602279
2  1.160454   1.160454
3 -0.602279  -2.232998
4 -0.597652   0.008966
Temp(c)      5
Ice cream    5
dtype: int64


In [58]:
sum?
# this will open up 'help' to the right!
# for some functions typing two question marks, i.e., ??, will give
# you the source file, so you can actually read the original Python
# code that underlies the function

# Another way is as follows:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [64]:
# Creating functions

def Func():  # On the next lines, it is important to use "2 space" (or a Tab) to be considered inside the function, otherwise 
                    # you will get an error message
  print(2+5)
print('hi')  #this is not inside the function as I did not push it forward with a tab (or two-space)


Func()
  


hi
7


In [66]:
def Func2(inp1,inp2):
  print(inp1**2 + inp2)

Func2(3,-1)


8


In [68]:
# Lambda function

funname = lambda x: x**3 -1 

funname(2)

7

In [99]:
# Factorial 
import numpy as np


def myfactorial(n):
  return np.prod(np.arange(1,n+1))


print(myfactorial(4))

#the other way to find factorial is using the "math" library
import math

print(math.factorial(3))

u=22
print(myfactorial(u), math.factorial(u))
#myfactorial does not work well with large numbers like u = 22



24
6
-1250660718674968576 1124000727777607680000


In [18]:
# Scope (locally, globally)
# Runtime + Restart runtime 

# Variables created inside a function are local (accessible only inside the function)
# Variables created outside a function are  global (accessible in or out of the function)

def funfun():
  x = 6  #(local scope) # x is defined locally inside this function. So if you call it out of funfun, it does not return anything
  y = 20 #(local scope)
  print(x)

x = 4
funfun()
# print(x) # it gives error if we had not defined x =4 two line above, because before that x was just defined locally inside funfun
print(x)

%whos

6
4
Variable   Type        Data/Info
--------------------------------
coinflip   function    <function coinflip at 0x7f38f9536d40>
funfun     function    <function funfun at 0x7f38f9536320>
np         module      <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
x          int         4


In [17]:
# Exercise: Write a function that flips a coin N times, and reports the average

import numpy as np

def coinflip(N):
  propCoinFlips = np.mean( np.random.randn(N)>0)
  print(str(N)+ ' ' + 'coin flips had' + ' ' + str(100*propCoinFlips) + '%' + ' ' + 'heads!')

coinflip(25)

25 coin flips had 44.0% heads!


In [21]:
# Copy
a = [4, 5]
b = a # this does not define a new variable 'b' and does not copy 'a' to 'b' (different from MATLAB)
      # in fact, 'b' is just a different name for 'a'.   'b' is simply a new referent to 'a'
b[0] = -1

print(a)  # The first element of 'a' will change as well
print(b)

[-1, 5]
[-1, 5]


In [24]:
# How to copy then??!!
c = a[:]   #this tells Python a copy of 'a' to the new variable 'c'
           # this method of copiness doesn't work in classes, or other kinds of objects (not global)

c[0]= 10
print(a)
print(c)


[-1, 5]
[10, 5]


In [27]:
# Copy import
import copy

a = { 'q': 1, 'w': 4 }
b = copy.deepcopy(a)    #We often use it in deep learning

b

{'q': 1, 'w': 4}

Object Oriented Programming (OOPs):

A **class** is a code template for creating objects. **Objects** have member variables and have behavior associated with them. In python a class is created by the keyword class. An object is created using the constructor of the class.



In [50]:
# Class: Blueprint for creating a set of attributes (variables) 
         # and methods (functions)
# Every class is going to produce multiple instances

class model(object):

  #contructor method  (methods of objects are nothing more than funcitons)
 def __init__(self,numlayers,numunits,name):
  self.layer   = numlayers   #attributes (variables)
  self.units   = numunits
  self.names   = name
  self.weights = 1
  
 def howManyUnits(self):
  totalUnits = self.layer * self.units
  print(f'There are {totalUnits} units in the mode.')

 def trainTheModel(self,x):
  self.weights += x
  return self.weights

 def __str__(self):
   return f'This is a {self.names} architecture.'
 

In [52]:
m1 = model(2,5,'CNN2')
m1.howManyUnits()

m1.trainTheModel(2.5)
str(m1)



There are 10 units in the mode.


'This is a CNN2 architecture.'

In [53]:
# Exercise: Create a new class
# 1) weights should be a random numbers matrix of size layers X units
# 2) change training method to multiply input X and add input Y


In [55]:
class model2(object):

  #contructor method  (methods of objects are nothing more than funcitons)
 def __init__(self,numlayers,numunits,name):
  self.layer   = numlayers   #attributes (variables)
  self.units   = numunits
  self.names   = name
  self.weights = np.random.randn(numlayers,self.units)
  
 def howManyUnits(self):
  totalUnits = self.layer * self.units
  print(f'There are {totalUnits} units in the mode.')

 def trainTheModel(self,x,y):
  self.weights = self.weights*x + y
 

 def __str__(self):
   return f'This is a {self.names} architecture.'

In [59]:
m2 = model2(2,3,'X')
m2.weights

array([[-1.45204399,  2.03079877, -0.46918816],
       [ 1.15776103, -0.14655767,  1.33710111]])

In [60]:
m2.trainTheModel(2,3)
m2.weights


array([[0.09591201, 7.06159753, 2.06162368],
       [5.31552207, 2.70688465, 5.67420222]])